AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MCPFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: mcp/dist/main.handler
      Runtime: nodejs22.x
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /mcp
            Method: get